apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v0.5.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.46.0
- name: silkroadprofessionals.azurecr.io/ocelot-api-gateway
  newTag: v0.11.0
- name: silkroadprofessionals.azurecr.io/mra-pages-api
  newTag: v0.10.0
resources:
- identity.yml
- jobs.yml
- getaway.yml
- pages.yml