apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v1.8.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.55.0
- name: silkroadprofessionals.azurecr.io/ocelot-api-gateway
  newTag: v0.26.0
- name: silkroadprofessionals.azurecr.io/mra-pages-api
  newTag: v0.20.0
- name: silkroadprofessionals.azurecr.io/mra-dotnet-compiler
  newTag: v0.8.0
resources:
- identity.yml
- jobs.yml
- getaway.yml
- pages.yml
- dotnetCompiler.yml