apiVersion: apps/v1
kind: Deployment
metadata:
  name: mra-identity-api-deployment
  namespace: mra
  labels:
    app: mra-identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mra-identity-api
  template:
    metadata:
      labels:
        app: mra-identity-api
    spec:
      containers:
      - name: mra-identity-api
        image: silkroadprofessionals.azurecr.io/mra-identity-api:v0.8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: AzureClientSecretValue
          valueFrom:
            secretKeyRef:
              name: azure-client-secret-value
              key: secretValue
---

apiVersion: v1
kind: Service
metadata:
  name: mra-identity-api-service
  namespace: mra
  labels:
    app: mra-identity-api
spec:
  selector:
    app: mra-identity-api
  ports:
    - name: http
      port: 5070
      targetPort: 80
      nodePort: 30700
      protocol: TCP
  type: NodePort
