apiVersion: apps/v1
kind: Deployment
metadata:
  name: mra-identity-api-deployment
  namespace: mra-staging
  labels:
    app: mra-identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mra-identity-api
  template:
    metadata:
      labels:
        app: mra-identity-api
    spec:
      containers:
      - name: mra-identity-api
        image: silkroadprofessionals.azurecr.io/mra-identity-api:v0.23.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: Environment
          value: Staging
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: AzureClientSecretValue
          valueFrom:
            secretKeyRef:
              name: azure-client-secret-value
              key: secretValue
        - name: AzureKeyVault__KeyVaultName
          value: Staging-Mra-Key-Vault
        - name: AzureKeyVault__AzureADApplicationId
          valueFrom:
            configMapKeyRef:
              name: mra-config
              key: AzureADApplicationId
        - name: AzureKeyVault__AzureADCertThumbprint
          valueFrom:
            configMapKeyRef:
              name: mra-config
              key: AzureADCertThumbprint
        - name: AzureKeyVault__AzureADDirectoryId
          valueFrom:
            configMapKeyRef:
              name: mra-config
              key: AzureADDirectoryId

      imagePullSecrets:
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: mra-identity-api-service
  namespace: mra-staging
  labels:
    app: mra-identity-api
spec:
  selector:
    app: mra-identity-api
  ports:
    - name: http
      port: 5070
      targetPort: 80
      protocol: TCP