apiVersion: apps/v1
kind: Deployment
metadata:
  name: mra-web-api-deployment
  namespace: mra
  labels:
    app: mra-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mra-web-api
  template:
    metadata:
      labels:
        app: mra-web-api
    spec:
      containers:
      - name: mra-web-api
        image: adheem/mra-web-api:v0.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: AzureClientSecretValue
          valueFrom:
            secretKeyRef:
              name: azure-client-secret-value
              key: secretValue
        - name: CS
          value: Server=192.168.1.17,1433;User ID=SA;Password=Sdfk&^^&!1231JS%%^@1112;Database=WebAPITest;Trusted_Connection=True;MultipleActiveResultSets=true;Integrated Security=false;TrustServerCertificate=True;
---

apiVersion: v1
kind: Service
metadata:
  name: mra-identity-api-service
  namespace: mra
  labels:
    app: mra-identity-api
spec:
  selector:
    app: mra-identity-api
  ports:
    - name: http
      port: 5080
      targetPort: 80
      nodePort: 30800
      protocol: TCP
  type: NodePort
