apiVersion: apps/v1
kind: Deployment
metadata:
  name: mra-web-api-deployment
  namespace: mra
  labels:
    app: mra-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mra-web-api
  template:
    metadata:
      labels:
        app: mra-web-api
    spec:
      containers:
      - name: mra-web-api
        image: silkroadprofessionals.azurecr.io/mra-web-api:v0.10.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: AzureClientSecretValue
          valueFrom:
            secretKeyRef:
              name: azure-client-secret-value
              key: secretValue
      imagePullSecrets:
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: mra-web-api-service
  namespace: mra
  labels:
    app: mra-web-api
spec:
  selector:
    app: mra-web-api
  ports:
    - name: http
      port: 5080
      targetPort: 80
      nodePort: 30800
      protocol: TCP
