apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway-deployment
  namespace: mra
  labels:
    app: ocelot-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
      - name: ocelot-api-gateway
        image: adheem/ocelot-api-gateway:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---

apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway-service
  namespace: mra
  labels:
    app: ocelot-api-gateway
spec:
  selector:
    app: ocelot-api-gateway
  ports:
    - name: http
      port: 8090
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
