apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway-deployment
  namespace: mra
  labels:
    app: ocelot-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      volumes:
      - name: srp-app-tls
        secret:
          secretName: srp-tls-cert-secret
      containers:
      - name: ocelot-api-gateway
        image: silkroadprofessionals.azurecr.io/ocelot-api-gateway:v1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        volumeMounts:
        - name: srp-app-tls
          mountPath: /secrets/tls-cert
          readOnly: true
        env:
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: ""
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /secrets/tls-cert/srp_tj.pfx
        - name: ASPNETCORE_URLS
          value: "https://+;http://+"
        - name: ASPNETCORE_HTTPS_PORT
          value: "443"
      imagePullSecrets:
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway-service
  namespace: mra
  labels:
    app: ocelot-api-gateway
spec:
  selector:
    app: ocelot-api-gateway
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP