apiVersion: apps/v1
kind: Deployment
metadata:
  name: mra-pages-api-deployment
  namespace: mra
  labels:
    app: mra-pages-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mra-pages-api
  template:
    metadata:
      labels:
        app: mra-pages-api
    spec:
      containers:
      - name: mra-pages-api
        image: silkroadprofessionals.azurecr.io/mra-pages-api:v0.35.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80

        - name: Environment
          valueFrom:
            configMapKeyRef:
              name: mra-prod-config
              key: Environment
        - name: TZ
          value: Asia/Karachi

        # azure key vault config data
        - name: AzureClientSecretValue
          valueFrom:
            secretKeyRef:
              name: azure-client-secret-value
              key: secretValue
        - name: AzureKeyVault__KeyVaultName
          valueFrom:
            configMapKeyRef:
              name: mra-prod-config
              key: KeyVaultName
        - name: AzureKeyVault__AzureADApplicationId
          valueFrom:
            configMapKeyRef:
              name: mra-prod-config
              key: AzureADApplicationId
        - name: AzureKeyVault__AzureADCertThumbprint
          valueFrom:
            configMapKeyRef:
              name: mra-prod-config
              key: AzureADCertThumbprint
        - name: AzureKeyVault__AzureADDirectoryId
          valueFrom:
            configMapKeyRef:
              name: mra-prod-config
              key: AzureADDirectoryId
      imagePullSecrets:
        - name: acr-secret