apiVersion: v1
kind: Service
metadata:
  name: mra-dotnet-compiler-service
  namespace: mra-staging
  labels:
    app: mra-dotnet-compiler
spec:
  clusterIP: 10.122.70.160
  selector:
    app: mra-web-api
  ports:
    - name: http
      port: 5090
      targetPort: 80
      protocol: TCP