apiVersion: v1
kind: Service
metadata:
  name: mra-dotnet-compiler-service
  namespace: mra
  labels:
    app: mra-dotnet-compiler
spec:
  clusterIP: 10.99.36.182
  selector:
    app: mra-dotnet-compiler
  ports:
    - name: http
      port: 5010
      targetPort: 80
      protocol: TCP