apiVersion: v1
kind: Service
metadata:
  name: mra-identity-api-service
  namespace: mra
  labels:
    app: mra-identity-api
spec:
  clusterIP: 10.99.36.181
  selector:
    app: mra-identity-api
  ports:
    - name: http
      port: 5070
      targetPort: 80
      protocol: TCP