apiVersion: v1
kind: Service
metadata:
  name: mra-web-api-service
  namespace: mra
  labels:
    app: mra-web-api
spec:
  clusterIP: 10.98.171.206
  selector:
    app: mra-web-api
  ports:
    - name: http
      port: 5080
      targetPort: 80
      protocol: TCP
