apiVersion: v1
kind: Service
metadata:
  name: mra-online-platform-api-service
  namespace: mra-staging
  labels:
    app: mra-online-platform-api
spec:
  clusterIP: 10.111.7.79
  selector:
    app: mra-online-platform-api
  ports:
    - name: http
      port: 5070
      targetPort: 80
      protocol: TCP