apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v0.5.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.45.0
- name: silkroadprofessionals.azurecr.io/ocelot-api-gateway
  newTag: v0.4.0
- name: silkroadprofessionals.azurecr.io/mra-pages-api
  newTag: v0.4.0
resources:
- identity.yml
- jobs.yml
- pages.yml