apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v0.35.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.37.0
resources:
- identity.yml
- jobs.yml