apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v0.7.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.48.0
- name: silkroadprofessionals.azurecr.io/mra-dotnet-compiler
  newTag: v0.0.0
resources:
- identity.yml
- jobs.yml
- dotnetCompiler.yml