apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: silkroadprofessionals.azurecr.io/mra-identity-api
    newTag: v0.7.0
  - name: silkroadprofessionals.azurecr.io/mra-web-api
    newTag: v0.49.0
  - name: silkroadprofessionals.azurecr.io/mra-online-platform-api
    newTag: v0.1.0
resources:
  - identity.yml
  - jobs.yml
  - onlinePlatform.yml