apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: silkroadprofessionals.azurecr.io/mra-identity-api
  newTag: v1.8.0
- name: silkroadprofessionals.azurecr.io/mra-web-api
  newTag: v0.55.0
  
  
  
  


- name: silkroadprofessionals.azurecr.io/mra-online-platform-api
  newTag: v1.7.0
- name: silkroadprofessionals.azurecr.io/mra-asset-management-api
  newTag: v0.12.0
resources:
 - identity.yml
 - jobs.yml
 - onlinePlatform.yml
 - assetsmanagement.yml