name: Repository Dispatch
on:
  repository_dispatch:
    types: [update]
jobs:
  versionUpdater:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
        
      - name: Update the Image Version
        uses: mikefarah/yq@master
        with:
          cmd: yq '(.images | select(.name == "silkroadprofessionals.azurecr.io/${{ github.event.client_payload.image }}") | .newTag) = ${{ github.event.client_payload.version }}' kustomization.yml

        working-directory: "./MRAInfrastructure/Environment/${{ github.event.client_payload.environment }}"
      
      - name: Commit Changes
        run: |
          cat kustomization.yml
          kustomize build . > ./Deployment/deployment.yml
          git add .
          git commit -m "Auto commit - ${{ github.sha }}"
          git status
        working-directory: "./MRAInfrastructure/Environment/${{ github.event.client_payload.environment }}"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}