name: Repository Dispatch
on:
  repository_dispatch:
    types: [update]
jobs:
  versionUpdater:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
      
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
        
      - name: Update Staging/Kustomization IdentityService tag version and update the files in resource
        run: |
          sed -i 's|newTag: .*|newTag: ${{ github.event.client_payload.version }}|' kustomization.yml
          kustomize build . > ../Deployment/deployment.yml

        working-directory: ./MRAInfrastructure/Environment/Staging/Kustomize

      - name: Update Production/Kustomization WebAPI tag version
        run: |
          sed -i 's|newTag: .*|newTag: ${{ github.event.client_payload.version }}|' kustomization.yml
          git add .
          git status
        working-directory: ./MRAInfrastructure/Environment/Production/Kustomize
      
      - name: Commit Changes
        run: |
          git commit -m "Auto commit - ${{ github.sha }}"
          git status

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}